apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0b3100c867a52fe3e
