apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
  labels:
    project: roboshop
    purpose: multicontainer-demo
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "10000"]