apiVersion: v1 
kind: Pod
metadata:
  name: resources
  lables:
    purpose: resource-demo
spec:
  containers:
  - name: nginx
    image: nginx 
    resources:
      requests:
        memory: "68mi"
        cpu: "100m"
      limits:
        memory: "128mi"
        cpu: "150m"