apiVersion: v1 
kind: Pod
metadata:
  name: env
  labels:
   purpose: env-demo
spec:
  containers:
  - name: almalinux
    image: almalinux:9
    command: ["sleep", "10000"]
    env:
    - name: course
      value: "kubernetes"
    - name: trainer
      value: "siva"