apiVersion: v1
kind: Service
metadata:
  name: clusterip
  labels:
    purpose: clusterip-demo
    project: roboshop
    env: dev
spec:
  selector:
    project: roboshop
    env: dev
    component: nginx 
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
---
apiVersion: v1 
kind: Pod
metadata:
  name: pod-clusterip
  labels:
    project: roboshop
    env: dev
    component: nginx
spec:
  containers:
  - name: nginx
    image: nginx
