apiVersion: v1 
kind: Service
metadata: 
  name: service-np 
  labels:
    purpose: demo service-np
spec:
  selector:
    project: roboshop
    env: dev
    component: service-np
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80


---
apiVersion: v1 
kind: Pod
metadata: 
  name: service-np
  labels:
    project: roboshop
    env: dev
    component: service-np
spec:
  containers:
    - name: nginx
      image: nginx