apiVersion: v1
kind: Service 
metadata:
  name: service-lb 
  labels:
    purpose: service-lb-demo 
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    env: dev
    component: service-lb
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Pod 
metadata:
  name: service-lb
  labels:
    project: roboshop
    env: dev
    component: service-lb
spec:
  containers:
  - name: nginx
    image: nginx
