apiVersion: v1
kind: Service
metadata:
  name: sc-headless-svc
  labels:
    purpose: demo
    env: dev
    project: roboshop
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    purpose: demo
    env: dev
    project: roboshop
---
apiVersion: v1
kind: Service
metadata:
  name: sc-normal-svc
  labels:
    purpose: demo
    env: dev
    project: roboshop
spec:
  selector:
    purpose: demo
    env: dev
    project: roboshop
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: state-less
spec:
  selector:
    matchLabels:
      purpose: demo
      env: dev
      project: roboshop
  serviceName: "sc-headless-svc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        purpose: demo
        env: dev
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi